# Informations sur ton site
title: Walid Ghouzza
email: walid.ghouzza@epitech.eu
description: Portfolio de développeur web - Étudiant Epitech

# Configuration des liens (Très important pour Epitech)
baseurl: "/portfolio" # Laisse vide pour le moment
url: "https://walidghg.github.io"

# Dossiers à ignorer lors de la construction du site
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
